let state={saved:[],notes:{}};let storageAvailable=true;try{const v=JSON.parse(localStorage.getItem('print-guide-v1'));if(v&&Array.isArray(v.saved)&&v.notes&&typeof v.notes==='object'){state.saved=v.saved.filter(id=>works.some(w=>w.id===id));for(const w of works)if(typeof v.notes[w.id]==='string')state.notes[w.id]=v.notes[w.id]}}catch{storageAvailable=false}
function persist(){try{localStorage.setItem('print-guide-v1',JSON.stringify(state))}catch{storageAvailable=false;toast('浏览器未允许保存，本次关闭后记录可能丢失。')}}
let toastTimer;function toast(text){const e=document.getElementById('toast');e.textContent=text;e.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.style.display='none',3500)}
function setSaved(id,value){if(!works.some(w=>w.id===id)||typeof value!=='boolean')throw Error('无效的作品或收藏状态');state.saved=state.saved.filter(x=>x!==id);if(value)state.saved.push(id);persist();render();return {id,saved:value}}
function card(w,notes=false){
 const article=document.createElement('article');article.className='art-card';article.id=(notes?'saved-':'work-')+w.id;
 const index=works.indexOf(w)+1;
 const meta=[w.year,w.medium,w.size].filter(Boolean).join(' / ');
 article.innerHTML=`<div class="card-body">${w.kind?`<span class="work-kind">${w.kind}</span>`:''}<div class="artist">${w.artist}</div><div class="title-row"><h3>${w.title}</h3><button class="favorite" aria-label="${state.saved.includes(w.id)?'取消收藏':'收藏'}《${w.title}》" aria-pressed="${state.saved.includes(w.id)}">${state.saved.includes(w.id)?'♥':'♡'}</button></div>${meta?`<div class="medium">${meta}</div>`:''}<p class="prompt">${w.summary}</p><details><summary>作品讲解</summary>${w.sections.map(s=>`<section class="explanation"><h4>${s.heading}</h4><p>${s.text}</p></section>`).join('')}<div class="source-links">${w.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title} ↗</a>`).join('')}</div></details></div>`;
 if(w.image){const box=document.createElement('a');box.className='art-image';box.href=w.image;box.target='_blank';box.rel='noopener noreferrer';box.setAttribute('aria-label','查看《'+w.title+'》大图');const img=document.createElement('img');img.src=w.image;img.alt=w.artist+'《'+w.title+'》';img.loading=index<=3?'eager':'lazy';const num=document.createElement('span');num.className='number';num.textContent=String(index).padStart(2,'0');box.append(img,num);article.prepend(box)}
 article.querySelector('.favorite').onclick=()=>{const next=!state.saved.includes(w.id);const opened=article.querySelector('details').open;setSaved(w.id,next);const updated=document.getElementById(article.id);if(updated){updated.querySelector('details').open=opened;updated.querySelector('.favorite').focus({preventScroll:true})}toast(next?'已收藏':'已取消收藏')};
 if(notes){const label=document.createElement('label');label.className='note-label';label.textContent='我的笔记';const ta=document.createElement('textarea');ta.className='note';ta.maxLength=2000;ta.placeholder='记录作品细节或感受';ta.value=state.notes[w.id]||'';ta.setAttribute('aria-label',w.title+'的笔记');ta.oninput=()=>{state.notes[w.id]=ta.value;persist()};label.appendChild(ta);article.querySelector('.card-body').appendChild(label)}return article
}
function render(){document.getElementById('art-grid').replaceChildren(...works.map(w=>card(w)));document.getElementById('saved-grid').replaceChildren(...works.filter(w=>state.saved.includes(w.id)).map(w=>card(w,true)));document.getElementById('saved-count').textContent=state.saved.length;document.getElementById('empty').hidden=state.saved.length>0}
function route(){const id=['guide','learn','visit','saved'].includes(location.hash.slice(1))?location.hash.slice(1):'guide';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==id);document.querySelectorAll('[data-tab]').forEach(el=>{if(el.dataset.tab===id)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
window.addEventListener('hashchange',route);document.getElementById('share').onclick=async()=>{const url=location.origin+location.pathname+'#guide';if(navigator.share){try{await navigator.share({title:'一起看版画 · 复数的魅力',text:'关山月美术馆国际版画展，重点作品讲解与参观信息。',url});return}catch(e){if(e.name==='AbortError')return}}try{await navigator.clipboard.writeText(url);toast('链接已复制')}catch{document.getElementById('share-url').value=url;document.getElementById('share-dialog').showModal();document.getElementById('share-url').select()}};
render();route();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_artwork_saved',title:'收藏或取消收藏展品',description:'在当前浏览器收藏或取消收藏一件展品。笔记与收藏不共享给其他访客。',inputSchema:{type:'object',properties:{id:{type:'string',enum:works.map(w=>w.id)},saved:{type:'boolean'}},required:['id','saved'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object')throw Error('需要作品ID和收藏状态');return setSaved(input.id,input.saved)}})).catch(()=>{})}catch{}}
